# Generated by Django 5.1.5 on 2025-04-27 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ufUserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's unique email", max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(help_text='Unique username with minimum 3 characters', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('full_name', models.CharField(max_length=100)),
                ('interests', models.JSONField(default=list, help_text='List of user interests')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('mid_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'ufuser_profile',
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['username'], name='idx_user_username')],
            },
        ),
    ]
