# Generated by Django 5.1.5 on 2025-04-27 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufuserprofile',
            name='username',
            field=models.CharField(help_text='Unique username with minimum 3 characters', max_length=512, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
