# Generated by Django 5.1.5 on 2025-04-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ufuserprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufuserprofile',
            name='token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
