# Generated by Django 5.1.5 on 2025-04-28 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ufuserprofile_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subjectId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='UploadedVideoLecture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('videoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('videoTitle', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='api.subject')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to='api.ufuserprofile')),
            ],
            options={
                'verbose_name': 'Uploaded Video Lecture',
                'verbose_name_plural': 'Uploaded Video Lectures',
                'db_table': 'uploaded_video_lecture',
            },
        ),
        migrations.CreateModel(
            name='LectureTranslation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('translationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sourceText', models.TextField()),
                ('translatedText', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('undone', 'Undone')], default='undone', max_length=10)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.uploadedvideolecture')),
            ],
            options={
                'verbose_name': 'Lecture Translation',
                'verbose_name_plural': 'Lecture Translations',
                'db_table': 'lecture_translation',
            },
        ),
    ]
