# Generated by Django 5.1.5 on 2025-04-30 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subject_uploadedvideolecture_lecturetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('storyId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('story', models.TextField(help_text="Learner's personal story or feedback")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_stories', to='api.ufuserprofile')),
            ],
            options={
                'verbose_name': 'Learner Story',
                'verbose_name_plural': 'Learner Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
