# Generated by Django 5.1.5 on 2025-04-19 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_created_at_userprofile_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('videoTitle', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('lectureCategory', models.CharField(max_length=100)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to='api.userprofile')),
            ],
        ),
    ]
