# Generated by Django 5.1.5 on 2025-05-01 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_learnerstories_delete_learnerstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('queryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_of_issue', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('feedback', 'Feedback')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue_detail', models.TextField(help_text="User's issue or query description")),
            ],
            options={
                'verbose_name': 'User Query',
                'verbose_name_plural': 'User Queries',
                'db_table': 'user_query',
            },
        ),
    ]
