# Generated by Django 5.1.5 on 2025-04-21 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_uploadedvideolecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTranslation',
            fields=[
                ('translationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sourceText', models.TextField()),
                ('translatedText', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('undone', 'Undone')], default='undone', max_length=10)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.uploadedvideolecture')),
            ],
        ),
    ]
