# Generated by Django 5.1.5 on 2025-05-03 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesBlog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('articleId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('oneLinerHeader', models.TextField(default='How Large Language Models Are Revolutionizing')),
                ('mainContent', models.TextField()),
            ],
            options={
                'verbose_name': 'Articles Blog',
                'verbose_name_plural': 'Articles Blogs',
                'db_table': 'articles_blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
