# Generated by Django 5.1.5 on 2025-05-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_articlesblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideolecture',
            name='video_file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
