# Generated by Django 5.1.5 on 2025-05-11 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_uploadedvideolecture_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('discussionId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='api.ufuserprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_discussions', to='api.ufuserprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='api.uploadedvideolecture')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
                'db_table': 'discussion',
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('replyId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.ufuserprofile')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.discussion')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_replies', to='api.ufuserprofile')),
            ],
            options={
                'verbose_name': 'Discussion Reply',
                'verbose_name_plural': 'Discussion Replies',
                'db_table': 'discussion_reply',
            },
        ),
    ]
